import React from "react";
import { Menu, Input } from "antd";
// import { ClickParam } from "antd/lib/menu";
import servicePath from "../model/serviceSvgPath";

const { SubMenu } = Menu;
const { Search } = Input;

const icon: any = servicePath;

const menuListFilter = [
  {
    groupLabel: "cache",
    groupName: "缓存服务",
    showLocation: 2,
    groupIndex: 0,
    cfgCompModelList: [
      {
        id: 11,
        compGroupId: 1,
        compType: "SNRS",
        compCname: "Zedis",
        compEname: "Zedis",
        compDesc: "兼容Redis协议的缓存和存储服务",
        connObj: "{}",
        connectedObject: {},
        connectedCheck: [
          {
            id: 54,
            compModelId: 11,
            connectedCompType: "JbossStandaloneKVM",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 55,
            compModelId: 11,
            connectedCompType: "NODEJS",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 56,
            compModelId: 11,
            connectedCompType: "JbossStandaloneKVMAI",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 57,
            compModelId: 11,
            connectedCompType: "TomcatDocker",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
        ],
        exportNumber: -1,
        showLocation: 2,
        status: 1,
      },
      {
        id: 23,
        compGroupId: 1,
        compType: "SNRSMulti",
        compCname: "Redis(多活)",
        compEname: "RedisMulti",
        compDesc: "Redis多活",
        connObj: "{}",
        connectedObject: {},
        connectedCheck: [
          {
            id: 80,
            compModelId: 23,
            connectedCompType: "JbossStandaloneKVM",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 81,
            compModelId: 23,
            connectedCompType: "NODEJS",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 82,
            compModelId: 23,
            connectedCompType: "JbossStandaloneKVMAI",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 83,
            compModelId: 23,
            connectedCompType: "TomcatDocker",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
        ],
        exportNumber: -1,
        showLocation: 2,
        status: 1,
      },
    ],
  },
  {
    groupLabel: "db",
    groupName: "数据库服务",
    showLocation: 2,
    groupIndex: 0,
    cfgCompModelList: [
      {
        id: 10,
        compGroupId: 2,
        compType: "DB2",
        compCname: "DB2",
        compEname: "DB2",
        compDesc: "基于v9.7.0.7、 v10.5.0.7版本的单机/高可用DB2数据库服务",
        connObj: "{}",
        connectedObject: {},
        connectedCheck: [
          {
            id: 51,
            compModelId: 10,
            connectedCompType: "JbossStandaloneKVM",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 52,
            compModelId: 10,
            connectedCompType: "NODEJS",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 53,
            compModelId: 10,
            connectedCompType: "JbossStandaloneKVMAI",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
        ],
        exportNumber: -1,
        showLocation: 2,
        status: 1,
      },
      {
        id: 22,
        compGroupId: 2,
        compType: "NGMySQLMulti",
        compCname: "Mysql(多活)",
        compEname: "MysqlMulti",
        compDesc: "Mysql多活服务",
        connObj: "{}",
        connectedObject: {},
        connectedCheck: [
          {
            id: 75,
            compModelId: 22,
            connectedCompType: "JbossStandaloneKVM",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 76,
            compModelId: 22,
            connectedCompType: "NODEJS",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 77,
            compModelId: 22,
            connectedCompType: "GO",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 78,
            compModelId: 22,
            connectedCompType: "JbossStandaloneKVMAI",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 79,
            compModelId: 22,
            connectedCompType: "TomcatDocker",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
        ],
        exportNumber: -1,
        showLocation: 2,
        status: 1,
      },
      {
        id: 8,
        compGroupId: 2,
        compType: "NGMySQL",
        compCname: "Mysql",
        compEname: "Mysql",
        compDesc: "单机/高可用MySQL数据库服务",
        connObj: "{}",
        connectedObject: {},
        connectedCheck: [
          {
            id: 40,
            compModelId: 8,
            connectedCompType: "JbossStandaloneKVM",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 42,
            compModelId: 8,
            connectedCompType: "NODEJS",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 43,
            compModelId: 8,
            connectedCompType: "GO",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 44,
            compModelId: 8,
            connectedCompType: "JbossStandaloneKVMAI",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 45,
            compModelId: 8,
            connectedCompType: "TomcatDocker",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
        ],
        exportNumber: -1,
        showLocation: 2,
        status: 1,
      },
      {
        id: 9,
        compGroupId: 2,
        compType: "PostgreSQL",
        compCname: "PostgreSQL",
        compEname: "PostgreSQL",
        compDesc: "基于10.7版本的PostgreSQL单机/高可用数据库服务",
        connObj: "{}",
        connectedObject: {},
        connectedCheck: [
          {
            id: 46,
            compModelId: 9,
            connectedCompType: "JbossStandaloneKVM",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 47,
            compModelId: 9,
            connectedCompType: "NODEJS",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 49,
            compModelId: 9,
            connectedCompType: "JbossStandaloneKVMAI",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 50,
            compModelId: 9,
            connectedCompType: "TomcatDocker",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
        ],
        exportNumber: -1,
        showLocation: 2,
        status: 1,
      },
      {
        id: 24,
        compGroupId: 2,
        compType: "MyCat",
        compCname: "MyCat",
        compEname: "MyCat",
        compDesc: "MyCat服务",
        connObj: "{}",
        connectedObject: {},
        connectedCheck: [
          {
            id: 84,
            compModelId: 24,
            connectedCompType: "JbossStandaloneKVM",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 85,
            compModelId: 24,
            connectedCompType: "NODEJS",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 86,
            compModelId: 24,
            connectedCompType: "GO",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 87,
            compModelId: 24,
            connectedCompType: "JbossStandaloneKVMAI",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
          {
            id: 88,
            compModelId: 24,
            connectedCompType: "TomcatDocker",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "app",
            status: 1,
          },
        ],
        exportNumber: -1,
        showLocation: 2,
        status: 1,
      },
    ],
  },
  {
    groupLabel: "app",
    groupName: "应用服务",
    showLocation: 0,
    groupIndex: 1,
    cfgCompModelList: [
      {
        id: 1,
        compGroupId: 3,
        compType: "JbossStandaloneKVM",
        compCname: "Wildfly",
        compEname: "Wildfly",
        compDesc: "单机版jboss",
        connObj: "{ 'DB2' : 0, 'NGMySQL' : 0, 'PostgreSQL' : 0, 'SNRS' : 0 }",
        connectedObject: { DB2: 0, NGMySQL: 0, PostgreSQL: 0, SNRS: 0 },
        connectedCheck: [
          {
            id: 1,
            compModelId: 1,
            connectedCompType: "NginxKVM",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "web",
            status: 1,
          },
          {
            id: 5,
            compModelId: 1,
            connectedCompType: "LOGBACK",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 6,
            compModelId: 1,
            connectedCompType: "PUBLICNETAGENT",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 7,
            compModelId: 1,
            connectedCompType: "LOGCOLLECT",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 8,
            compModelId: 1,
            connectedCompType: "SPM",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 67,
            compModelId: 1,
            connectedCompType: "LB",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "net",
            status: 1,
          },
        ],
        exportNumber: 0,
        showLocation: 0,
        status: 1,
      },
      {
        id: 5,
        compGroupId: 3,
        compType: "JbossStandaloneKVMAI",
        compCname: "Wildfly_AI",
        compEname: "Wildfly_AI",
        compDesc: "单机版AIjboss",
        connObj:
          "{ 'JbossStandaloneKVM' : 1,'DB2' : 0, 'NGMySQL' : 0, 'PostgreSQL' : 0, 'SNRS' : 0 }",
        connectedObject: {
          JbossStandaloneKVM: 1,
          DB2: 0,
          NGMySQL: 0,
          PostgreSQL: 0,
          SNRS: 0,
        },
        connectedCheck: [
          {
            id: 27,
            compModelId: 5,
            connectedCompType: "NginxKVM",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "web",
            status: 1,
          },
          {
            id: 30,
            compModelId: 5,
            connectedCompType: "LOGBACK",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 31,
            compModelId: 5,
            connectedCompType: "PUBLICNETAGENT",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 32,
            compModelId: 5,
            connectedCompType: "LOGCOLLECT",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 33,
            compModelId: 5,
            connectedCompType: "SPM",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 71,
            compModelId: 5,
            connectedCompType: "LB",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "net",
            status: 1,
          },
        ],
        exportNumber: 0,
        showLocation: 0,
        status: 1,
      },
      {
        id: 2,
        compGroupId: 3,
        compType: "NODEJS",
        compCname: "Nodejs",
        compEname: "Nodejs",
        compDesc: "NODEJS",
        connObj: "{ 'SNRS' : 0 }",
        connectedObject: { SNRS: 0 },
        connectedCheck: [
          {
            id: 9,
            compModelId: 2,
            connectedCompType: "NginxKVM",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "web",
            status: 1,
          },
          {
            id: 12,
            compModelId: 2,
            connectedCompType: "LOGBACK",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 13,
            compModelId: 2,
            connectedCompType: "PUBLICNETAGENT",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 14,
            compModelId: 2,
            connectedCompType: "LOGCOLLECT",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 68,
            compModelId: 2,
            connectedCompType: "LB",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "net",
            status: 1,
          },
        ],
        exportNumber: 0,
        showLocation: 0,
        status: 1,
      },
      {
        id: 3,
        compGroupId: 3,
        compType: "GO",
        compCname: "GO",
        compEname: "GO",
        compDesc: "GO",
        connObj: "{ 'NGMySQL' : 0 }",
        connectedObject: { NGMySQL: 0 },
        connectedCheck: [
          {
            id: 16,
            compModelId: 3,
            connectedCompType: "NginxKVM",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "web",
            status: 1,
          },
          {
            id: 19,
            compModelId: 3,
            connectedCompType: "LOGBACK",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 20,
            compModelId: 3,
            connectedCompType: "PUBLICNETAGENT",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 21,
            compModelId: 3,
            connectedCompType: "LOGCOLLECT",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 69,
            compModelId: 3,
            connectedCompType: "LB",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "net",
            status: 1,
          },
        ],
        exportNumber: 0,
        showLocation: 0,
        status: 1,
      },
      {
        id: 4,
        compGroupId: 3,
        compType: "TomcatDocker",
        compCname: "Tomcat(容器服务)",
        compEname: "Tomcat",
        compDesc: "tomcat容器",
        connObj: "{ 'NGMySQL' : 0, 'PostgreSQL' : 0, 'SNRS' : 0 }",
        connectedObject: { NGMySQL: 0, PostgreSQL: 0, SNRS: 0 },
        connectedCheck: [
          {
            id: 25,
            compModelId: 4,
            connectedCompType: "LOGCOLLECT",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 26,
            compModelId: 4,
            connectedCompType: "PUBLICNETAGENT",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 65,
            compModelId: 4,
            connectedCompType: "NginxKVM",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "web",
            status: 1,
          },
          {
            id: 70,
            compModelId: 4,
            connectedCompType: "LB",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "net",
            status: 1,
          },
        ],
        exportNumber: 0,
        showLocation: 0,
        status: 1,
      },
    ],
  },
  {
    groupLabel: "web",
    groupName: "WEB服务",
    showLocation: 1,
    groupIndex: 2,
    cfgCompModelList: [
      {
        id: 6,
        compGroupId: 4,
        compType: "NginxKVM",
        compCname: "Suengine",
        compEname: "Suengine",
        compDesc:
          "苏宁定制版nginx，专门和wildfly服务组合使用，实现对WildFly server的HTTP代理分发",
        connObj:
          "{ 'GO' : 1, 'JbossStandaloneKVM' : 1, 'JbossStandaloneKVMAI' : 1, 'NODEJS' : 1, 'TomcatDocker' : 1 }",
        connectedObject: {
          GO: 1,
          JbossStandaloneKVM: 1,
          JbossStandaloneKVMAI: 1,
          NODEJS: 1,
          TomcatDocker: 1,
        },
        connectedCheck: [
          {
            id: 36,
            compModelId: 6,
            connectedCompType: "LOGCOLLECT",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 63,
            compModelId: 6,
            connectedCompType: "LOGBACK",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 72,
            compModelId: 6,
            connectedCompType: "LB",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "net",
            status: 1,
          },
        ],
        exportNumber: 1,
        showLocation: 1,
        status: 1,
      },
      {
        id: 7,
        compGroupId: 4,
        compType: "NginxDocker",
        compCname: "Nginx(容器服务)",
        compEname: "Nginx",
        compDesc: "nginx容器",
        connObj: "{}",
        connectedObject: {},
        connectedCheck: [
          {
            id: 62,
            compModelId: 7,
            connectedCompType: "LOGCOLLECT",
            connectedNum: 1,
            notConnected: "[]",
            groupLabel: "strategy",
            status: 1,
          },
          {
            id: 73,
            compModelId: 7,
            connectedCompType: "LB",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "net",
            status: 1,
          },
        ],
        exportNumber: 0,
        showLocation: 0,
        status: 1,
      },
    ],
  },
  {
    groupLabel: "net",
    groupName: "网络服务",
    showLocation: 1,
    groupIndex: 3,
    cfgCompModelList: [
      {
        id: 21,
        compGroupId: 5,
        compType: "LB",
        compCname: "LB",
        compEname: "LB",
        compDesc: "支持TCP/UDP协议",
        connObj:
          "{  'vm' : 1,'GO' : 1, 'JbossStandaloneKVM' : 1, 'JbossStandaloneKVMAI' : 1, 'NODEJS' : 1, 'NginxDocker' : 1, 'NginxKVM' : 1, 'TomcatDocker' : 1 }",
        connectedObject: {
          vm: 1,
          GO: 1,
          JbossStandaloneKVM: 1,
          JbossStandaloneKVMAI: 1,
          NODEJS: 1,
          NginxDocker: 1,
          NginxKVM: 1,
          TomcatDocker: 1,
        },
        connectedCheck: [
          {
            id: 58,
            compModelId: 21,
            connectedCompType: "DNS",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "net",
            status: 1,
          },
        ],
        exportNumber: 1,
        showLocation: 1,
        status: 1,
      },
      {
        id: 14,
        compGroupId: 5,
        compType: "DNS",
        compCname: "域名解析",
        compEname: "DNS",
        compDesc: "仅支持内网域名解析",
        connObj: "{ 'LB' : 1 }",
        connectedObject: { LB: 1 },
        connectedCheck: [],
        exportNumber: 1,
        showLocation: 1,
        status: 1,
      },
    ],
  },
  {
    groupLabel: "strategy",
    groupName: "策略服务",
    showLocation: 4,
    groupIndex: 1,
    cfgCompModelList: [
      {
        id: 16,
        compGroupId: 6,
        compType: "PUBLICNETAGENT",
        compCname: "公网代理",
        compEname: "publicnetagent",
        compDesc: "适用于wildfly服务器访问公网场景",
        connObj:
          "{ 'JbossStandaloneKVM' : 1, 'NODEJS' : 1, 'GO' : 1, 'JbossStandaloneKVMAI' : 1, 'TomcatDocker' : 1 }",
        connectedObject: {
          JbossStandaloneKVM: 1,
          NODEJS: 1,
          GO: 1,
          JbossStandaloneKVMAI: 1,
          TomcatDocker: 1,
        },
        connectedCheck: [],
        exportNumber: 1,
        showLocation: 4,
        status: 1,
      },
      {
        id: 17,
        compGroupId: 6,
        compType: "SPM",
        compCname: "调用链监控",
        compEname: "spm",
        compDesc: "服务端调用链监控服务",
        connObj: "{ 'JbossStandaloneKVM' : 1, 'JbossStandaloneKVMAI' : 1 }",
        connectedObject: { JbossStandaloneKVM: 1, JbossStandaloneKVMAI: 1 },
        connectedCheck: [],
        exportNumber: 1,
        showLocation: 4,
        status: 1,
      },
      {
        id: 18,
        compGroupId: 6,
        compType: "LOGCOLLECT",
        compCname: "日志采集",
        compEname: "logcollect",
        compDesc: "日志采集",
        connObj:
          "{ 'JbossStandaloneKVM' : 1, 'NginxKVM' : 1, 'NginxDocker' : 1, 'TomcatDocker' : 1, 'JbossStandaloneKVMAI' : 1, 'NODEJS' : 1, 'GO' : 1 }",
        connectedObject: {
          JbossStandaloneKVM: 1,
          NginxKVM: 1,
          NginxDocker: 1,
          TomcatDocker: 1,
          JbossStandaloneKVMAI: 1,
          NODEJS: 1,
          GO: 1,
        },
        connectedCheck: [],
        exportNumber: 1,
        showLocation: 4,
        status: 1,
      },
    ],
  },
  {
    groupLabel: "common",
    groupName: "通用服务",
    showLocation: 2,
    groupIndex: 1,
    cfgCompModelList: [
      {
        id: 19,
        compGroupId: 7,
        compType: "vm",
        compCname: "ECS(裸机)",
        compEname: "ECS",
        compDesc: "通用虚拟机服务，用于申请裸机、JDK、Nginx等非服务化机器",
        connObj: "{}",
        connectedObject: {},
        connectedCheck: [
          {
            id: 74,
            compModelId: 19,
            connectedCompType: "LB",
            connectedNum: 0,
            notConnected: "[]",
            groupLabel: "net",
            status: 1,
          },
        ],
        exportNumber: 0,
        showLocation: 0,
        status: 1,
      },
    ],
  },
];

interface Props {}
const LeftSide: React.FC<Props> = () => {
  const onChange = (e: React.ChangeEvent<HTMLInputElement>): void => {
    console.log("click ", e);
  };
  const handleClick = (e: any): void => {
    console.log("click ", e);
  };
  return (
    <div className="LeftSide">
      <Search
        style={{ marginBottom: 8 }}
        placeholder="Search"
        onChange={onChange}
      />
      <Menu
        onClick={handleClick}
        style={{
          height: "100vh",
          overflow: "hiden",
          overflowY: "auto",
          border: "1px solid blue",
        }}
        defaultSelectedKeys={["1"]}
        defaultOpenKeys={[
          "cache",
          "db",
          "app",
          "web",
          "net",
          "strategy",
          "common",
        ]}
        mode="inline"
      >
        {menuListFilter.map((item: any) => (
          <SubMenu key={item.groupLabel} title={<span>{item.groupName}</span>}>
            {item.cfgCompModelList.map((el: any) => (
              <Menu.Item key={el.compEname}>
                <div style={{ height: "40px" }}>
                  <svg
                    style={{
                      width: "1.5em",
                      height: "1.5em",
                      verticalAlign: "10px",
                      fill: "#000000",
                    }}
                    viewBox="0 0 40 40"
                    version="1.1"
                    xmlns="http://www.w3.org/2000/svg"
                    p-id="916"
                  >
                    <path d={icon[el.compType]} />
                  </svg>
                  <span style={{ verticalAlign: "16px", marginLeft: "8px" }}>
                    {el.compCname}
                  </span>
                </div>
              </Menu.Item>
            ))}
          </SubMenu>
        ))}
      </Menu>
    </div>
  );
};
export default LeftSide;
